[settings]
    identifier = "distribution"

[config]

    [config.zsh]
        from = ".zshrc"

    [config.Xresources]
        from = ".Xresources"

    [config.bash_git]
        from = ".bash_git"

    [config.gitconfig]
        from = ".gitconfig"

    [config.i3_config]
        from = ".i3/config"

    [config.i3_blocks]
        from = ".i3/i3blocks.conf"

    [config.i3_blocks_scripts]
        from = ".i3/blocks"

    [config.i3_scripts]
        from = ".i3/scripts"

    [config.terminator]
        from = ".config/terminator/config"

    [config.background]
        from = 'Pictures/Jzn5hwl-epic-desktop-backgrounds.jpg'
